// Code generated by goctl. DO NOT EDIT.
package types

type Order struct {
	Id        uint32 `json:"id"`
	UserId    uint32 `json:"userId"`
	ProductId uint32 `json:"productId"`
	CreatedAt uint32 `json:"createdAt"`
}

type Product struct {
	Id        uint32  `json:"id"`
	Name      string  `json:"name"`
	Price     float32 `json:"price"`
	CreatedAt uint32  `json:"createdAt"`
}

type User struct {
	Id           uint32 `json:"id"`
	Login        string `json:"login"`
	RoleId       uint32 `json:"roleId"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    uint32 `json:"createdAt"`
}

type CreateProductReq struct {
	Name  string  `json:"name"`
	Price float32 `json:"price"`
}

type CreateProductResp struct {
	ProductId uint32 `json:"productId"`
}

type DeleteProductReq struct {
	ProductId uint32 `path:"productId"`
}

type DeleteProductResp struct {
	StatusCode uint32 `json:"statusCode"`
	Message    string `json:"message"`
}

type GetOrdersReq struct {
}

type GetOrdersResp struct {
	Orders []Order `json:"orders"`
}

type GetProductByIdReq struct {
	ProductId uint32 `path:"productId"`
}

type GetProductByIdResp struct {
	Product Product `json:"product"`
}

type GetProductsReq struct {
}

type GetProductsResp struct {
	Products []Product `json:"products"`
}

type SignInReq struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type SignInResp struct {
	Token string `json:"token"`
}

type SignUpReq struct {
	Login    string `json:"login"`
	RoleId   uint32 `json:"roleId"`
	Password string `json:"password"`
}

type SignUpResp struct {
	UserId uint32 `json:"userId"`
}

type UpdateProductReq struct {
	Id    uint32  `json:"id"`
	Name  string  `json:"name,optional"`
	Price float32 `json:"price,optional"`
}

type UpdateProductResp struct {
	ProductId uint32 `json:"productId"`
}
