// Code generated by goctl. DO NOT EDIT.
// Source: auth.proto

package server

import (
	"context"

	"github.com/Guvanchhojamov/gozero-app/gateway/services/authorization/rpc/internal/logic"
	"github.com/Guvanchhojamov/gozero-app/gateway/services/authorization/rpc/internal/svc"
	"github.com/Guvanchhojamov/gozero-app/gateway/services/authorization/rpc/v1"
)

type UserAuthServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedUserAuthServiceServer
}

func NewUserAuthServiceServer(svcCtx *svc.ServiceContext) *UserAuthServiceServer {
	return &UserAuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserAuthServiceServer) SignUp(ctx context.Context, in *v1.SignUpRequest) (*v1.SignUpResponse, error) {
	l := logic.NewSignUpLogic(ctx, s.svcCtx)
	return l.SignUp(in)
}

func (s *UserAuthServiceServer) SignIn(ctx context.Context, in *v1.SignInRequest) (*v1.SignInResponse, error) {
	l := logic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}
