// Code generated by goctl. DO NOT EDIT.
// Source: orders.proto

package server

import (
	"context"

	"github.com/Guvanchhojamov/gozero-app/gateway/services/orders/rpc/internal/logic"
	"github.com/Guvanchhojamov/gozero-app/gateway/services/orders/rpc/internal/svc"
	"github.com/Guvanchhojamov/gozero-app/gateway/services/orders/rpc/v1"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) GetOrders(ctx context.Context, in *v1.GetOrdersRequest) (*v1.GetOrdersResponse, error) {
	l := logic.NewGetOrdersLogic(ctx, s.svcCtx)
	return l.GetOrders(in)
}
