version: '3.3'
services:
  db-gozero:
    image: postgres:16-alpine
    container_name: db-gozero
    restart: always
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=abc12345
      - POSTGRES_DB=testdb
    ports:
      - '5464:5432'

  redis-gozero:
    container_name: redis-gozero
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6369:6379

  etcd-gozero:
    container_name: etcd-gozero
    image: bitnami/etcd:3.5.9
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380

volumes:
  gozero-db-storage:
